[toolchain]
anchor_version = "0.27.0"
solana_version = "1.17.9"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.devnet]
sld = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
sai = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.localnet]
sld = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
sai = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/dusty/.config/solana/id.json"

[workspace]
members = ["programs/sai", "programs/sld"]

[scripts]
create_cdp = "node src/scripts/create_cdp.js"
create_proposal = "node src/scripts/create_proposal.js"
initialize = "node src/scripts/initialize.js"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/"

[compiler]
solana_version = "1.17.9"
anchor_version = "0.27.0"
